name: Check merge

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Starting Bun 1
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Build all
        run: bun run build

  typecheck:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Starting Bun 1
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Build all
        run: bun run build

      - name: Typecheck
        run: bun run typecheck
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Starting Bun 1
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Build all
        run: bun run build

      - name: Typecheck
        run: bun run test
